export const MOCK_ROUNDS = [
  {
    id: "mock-1",
    instrument_type: "safe",
    raise_amount: 1200000,
    amount_raised: 864000,
    min_check_size: 10000,
    close_date: "2026-04-25",
    traction_metrics: { mrr: 42000, growth_rate_pct: 38, users: 1200 },
    pitch_deck_url: null,
    pitch_deck_filename: "arcana-deck.pdf",
    one_pager_url: null,
    demo_link: null,
    existing_investors: ["First Round Capital", "Naval Ravikant"],
    visibility: "public",
    status: "live",
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-04-06T00:00:00Z",
    founder_profiles: {
      id: "fp-1",
      company_name: "Arcana AI",
      one_liner: "AI-native legal research for solo practitioners",
      sector: ["AI / ML", "SaaS"],
      calendar_link: "https://calendly.com/arcana-ai/30min",
      company_website: "https://arcana.ai",
      accelerator_affiliations: ["YC W26"],
      profiles: {
        id: "p-1",
        full_name: "Sarah Chen",
        avatar_url: null,
        linkedin_url: "https://linkedin.com/in/sarahchen",
      },
    },
  },
  {
    id: "mock-2",
    instrument_type: "safe",
    raise_amount: 2500000,
    amount_raised: 1125000,
    min_check_size: 25000,
    close_date: "2026-05-15",
    traction_metrics: { arr: 118000, users: 34, growth_rate_pct: 22 },
    pitch_deck_url: null,
    pitch_deck_filename: "vaultic-deck.pdf",
    one_pager_url: null,
    demo_link: null,
    existing_investors: ["Lux Capital"],
    visibility: "public",
    status: "live",
    created_at: "2026-03-28T00:00:00Z",
    updated_at: "2026-04-05T00:00:00Z",
    founder_profiles: {
      id: "fp-2",
      company_name: "Vaultic",
      one_liner: "Supply chain risk intelligence for mid-market manufacturers",
      sector: ["SaaS", "Logistics / Supply Chain"],
      calendar_link: "https://cal.com/vaultic/intro",
      company_website: "https://vaultic.io",
      accelerator_affiliations: ["Techstars 2025"],
      profiles: {
        id: "p-2",
        full_name: "Marcus Rivera",
        avatar_url: null,
        linkedin_url: "https://linkedin.com/in/marcusrivera",
      },
    },
  },
  {
    id: "mock-3",
    instrument_type: "safe_mfn",
    raise_amount: 800000,
    amount_raised: 704000,
    min_check_size: 5000,
    close_date: "2026-04-18",
    traction_metrics: { users: 14, retention_pct: 92, revenue: 28000 },
    pitch_deck_url: null,
    pitch_deck_filename: "nudge-health-deck.pdf",
    one_pager_url: null,
    demo_link: "https://loom.com/share/nudge-demo",
    existing_investors: ["Andreessen Horowitz Scout", "Elad Gil"],
    visibility: "public",
    status: "closing",
    created_at: "2026-03-15T00:00:00Z",
    updated_at: "2026-04-06T00:00:00Z",
    founder_profiles: {
      id: "fp-3",
      company_name: "Nudge Health",
      one_liner: "Behavioral nudges that cut patient no-show rates by 60%",
      sector: ["Health / Biotech", "AI / ML"],
      calendar_link: "https://calendly.com/nudge-health/founder",
      company_website: "https://nudgehealth.co",
      accelerator_affiliations: ["On Deck Health"],
      profiles: {
        id: "p-3",
        full_name: "Priya Patel",
        avatar_url: null,
        linkedin_url: "https://linkedin.com/in/priyapatel",
      },
    },
  },
  {
    id: "mock-4",
    instrument_type: "convertible_note",
    raise_amount: 1800000,
    amount_raised: 360000,
    min_check_size: 15000,
    close_date: "2026-05-30",
    traction_metrics: { mrr: 18000, growth_rate_pct: 45, dau: 850 },
    pitch_deck_url: null,
    pitch_deck_filename: "carbon-deck.pdf",
    one_pager_url: null,
    demo_link: null,
    existing_investors: ["Climate Capital"],
    visibility: "public",
    status: "live",
    created_at: "2026-04-03T00:00:00Z",
    updated_at: "2026-04-06T00:00:00Z",
    founder_profiles: {
      id: "fp-4",
      company_name: "CarbonLedger",
      one_liner: "Automated carbon accounting for SMBs that actually works",
      sector: ["Climate / Energy", "SaaS"],
      calendar_link: "https://cal.com/carbonledger/chat",
      company_website: "https://carbonledger.com",
      accelerator_affiliations: ["Greentown Labs"],
      profiles: {
        id: "p-4",
        full_name: "James Okafor",
        avatar_url: null,
        linkedin_url: "https://linkedin.com/in/jamesokafor",
      },
    },
  },
  {
    id: "mock-5",
    instrument_type: "safe",
    raise_amount: 500000,
    amount_raised: 125000,
    min_check_size: 5000,
    close_date: "2026-06-01",
    traction_metrics: { users: 3200, mau: 2100, growth_rate_pct: 30 },
    pitch_deck_url: null,
    pitch_deck_filename: "studypal-deck.pdf",
    one_pager_url: null,
    demo_link: null,
    existing_investors: [],
    visibility: "public",
    status: "live",
    created_at: "2026-04-04T00:00:00Z",
    updated_at: "2026-04-06T00:00:00Z",
    founder_profiles: {
      id: "fp-5",
      company_name: "StudyPal",
      one_liner: "AI study groups that match college students by learning style",
      sector: ["EdTech", "AI / ML"],
      calendar_link: "https://calendly.com/studypal/30min",
      company_website: "https://studypal.app",
      accelerator_affiliations: [],
      profiles: {
        id: "p-5",
        full_name: "Alex Kim",
        avatar_url: null,
        linkedin_url: "https://linkedin.com/in/alexkim",
      },
    },
  },
  {
    id: "mock-6",
    instrument_type: "priced_round",
    raise_amount: 3000000,
    amount_raised: 1800000,
    min_check_size: 50000,
    close_date: "2026-05-10",
    traction_metrics: { arr: 420000, users: 89, growth_rate_pct: 18 },
    pitch_deck_url: null,
    pitch_deck_filename: "paybridge-deck.pdf",
    one_pager_url: null,
    demo_link: null,
    existing_investors: ["Stripe", "Abstract Ventures"],
    visibility: "public",
    status: "live",
    created_at: "2026-03-20T00:00:00Z",
    updated_at: "2026-04-05T00:00:00Z",
    founder_profiles: {
      id: "fp-6",
      company_name: "PayBridge",
      one_liner: "Cross-border B2B payments for African exporters",
      sector: ["Fintech"],
      calendar_link: "https://cal.com/paybridge/investor",
      company_website: "https://paybridge.co",
      accelerator_affiliations: ["YC S25", "Google for Startups"],
      profiles: {
        id: "p-6",
        full_name: "Amara Diallo",
        avatar_url: null,
        linkedin_url: "https://linkedin.com/in/amaradiallo",
      },
    },
  },
];

export const MOCK_INTERACTIONS = [
  { id: "int-1", round_drop_id: "mock-3", investor_profile_id: "inv-1", action: "interested", created_at: "2026-04-05T10:00:00Z", updated_at: "2026-04-05T10:00:00Z" },
  { id: "int-2", round_drop_id: "mock-1", investor_profile_id: "inv-1", action: "tracked", created_at: "2026-04-04T15:00:00Z", updated_at: "2026-04-04T15:00:00Z" },
  { id: "int-3", round_drop_id: "mock-6", investor_profile_id: "inv-1", action: "viewed", created_at: "2026-04-06T08:00:00Z", updated_at: "2026-04-06T08:00:00Z" },
];

export const MOCK_FOUNDER_ROUNDS = [
  {
    id: "fr-1",
    instrument_type: "safe",
    raise_amount: 1200000,
    amount_raised: 864000,
    min_check_size: 10000,
    close_date: "2026-04-25",
    status: "live",
    valuation_cap: 10000000,
    discount_percent: null,
    traction_metrics: { mrr: 42000, growth_rate_pct: 38, users: 1200 },
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-04-06T00:00:00Z",
  },
  {
    id: "fr-2",
    instrument_type: "safe",
    raise_amount: 500000,
    amount_raised: 500000,
    min_check_size: 5000,
    close_date: "2025-12-15",
    status: "closed",
    valuation_cap: 6000000,
    discount_percent: 20,
    traction_metrics: { users: 300, mrr: 8000 },
    created_at: "2025-10-01T00:00:00Z",
    updated_at: "2025-12-15T00:00:00Z",
  },
];
