export const MOCK_ROUNDS = [
  {
    id: "mock-1",
    instrument_type: "safe",
    raise_amount: 1200000,
    amount_raised: 864000,
    min_check_size: 10000,
    close_date: "2026-04-25",
    traction_metrics: { mrr: 42000, growth_rate_pct: 38, users: 1200 },
    pitch_deck_url: null,
    pitch_deck_filename: "arcana-deck.pdf",
    one_pager_url: null,
    demo_link: null,
    existing_investors: ["First Round Capital", "Naval Ravikant"],
    visibility: "public",
    status: "live",
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-04-06T00:00:00Z",
    founder_profiles: {
      id: "fp-1",
      company_name: "Arcana AI",
      one_liner: "AI-native legal research for solo practitioners",
      sector: ["AI / ML", "SaaS"],
      calendar_link: "https://calendly.com/arcana-ai/30min",
      company_website: "https://arcana.ai",
      accelerator_affiliations: ["YC W26"],
      profiles: {
        id: "p-1",
        full_name: "Sarah Chen",
        avatar_url: null,
        linkedin_url: "https://linkedin.com/in/sarahchen",
      },
    },
  },
  {
    id: "mock-2",
    instrument_type: "safe",
    raise_amount: 2500000,
    amount_raised: 1125000,
    min_check_size: 25000,
    close_date: "2026-05-15",
    traction_metrics: { arr: 118000, users: 34, growth_rate_pct: 22 },
    pitch_deck_url: null,
    pitch_deck_filename: "vaultic-deck.pdf",
    one_pager_url: null,
    demo_link: null,
    existing_investors: ["Lux Capital"],
    visibility: "public",
    status: "live",
    created_at: "2026-03-28T00:00:00Z",
    updated_at: "2026-04-05T00:00:00Z",
    founder_profiles: {
      id: "fp-2",
      company_name: "Vaultic",
      one_liner: "Supply chain risk intelligence for mid-market manufacturers",
      sector: ["SaaS", "Logistics / Supply Chain"],
      calendar_link: "https://cal.com/vaultic/intro",
      company_website: "https://vaultic.io",
      accelerator_affiliations: ["Techstars 2025"],
      profiles: {
        id: "p-2",
        full_name: "Marcus Rivera",
        avatar_url: null,
        linkedin_url: "https://linkedin.com/in/marcusrivera",
      },
    },
  },
  {
    id: "mock-3",
    instrument_type: "safe_mfn",
    raise_amount: 800000,
    amount_raised: 704000,
    min_check_size: 5000,
    close_date: "2026-04-18",
    traction_metrics: { users: 14, retention_pct: 92, revenue: 28000 },
    pitch_deck_url: null,
    pitch_deck_filename: "nudge-health-deck.pdf",
    one_pager_url: null,
    demo_link: "https://loom.com/share/nudge-demo",
    existing_investors: ["Andreessen Horowitz Scout", "Elad Gil"],
    visibility: "public",
    status: "closing",
    created_at: "2026-03-15T00:00:00Z",
    updated_at: "2026-04-06T00:00:00Z",
    founder_profiles: {
      id: "fp-3",
      company_name: "Nudge Health",
      one_liner: "Behavioral nudges that cut patient no-show rates by 60%",
      sector: ["Health / Biotech", "AI / ML"],
      calendar_link: "https://calendly.com/nudge-health/founder",
      company_website: "https://nudgehealth.co",
      accelerator_affiliations: ["On Deck Health"],
      profiles: {
        id: "p-3",
        full_name: "Priya Patel",
        avatar_url: null,
        linkedin_url: "https://linkedin.com/in/priyapatel",
      },
    },
  },
  {
    id: "mock-4",
    instrument_type: "convertible_note",
    raise_amount: 1800000,
    amount_raised: 360000,
    min_check_size: 15000,
    close_date: "2026-05-30",
    traction_metrics: { mrr: 18000, growth_rate_pct: 45, dau: 850 },
    pitch_deck_url: null,
    pitch_deck_filename: "carbon-deck.pdf",
    one_pager_url: null,
    demo_link: null,
    existing_investors: ["Climate Capital"],
    visibility: "public",
    status: "live",
    created_at: "2026-04-03T00:00:00Z",
    updated_at: "2026-04-06T00:00:00Z",
    founder_profiles: {
      id: "fp-4",
      company_name: "CarbonLedger",
      one_liner: "Automated carbon accounting for SMBs that actually works",
      sector: ["Climate / Energy", "SaaS"],
      calendar_link: "https://cal.com/carbonledger/chat",
      company_website: "https://carbonledger.com",
      accelerator_affiliations: ["Greentown Labs"],
      profiles: {
        id: "p-4",
        full_name: "James Okafor",
        avatar_url: null,
        linkedin_url: "https://linkedin.com/in/jamesokafor",
      },
    },
  },
  {
    id: "mock-5",
    instrument_type: "safe",
    raise_amount: 500000,
    amount_raised: 125000,
    min_check_size: 5000,
    close_date: "2026-06-01",
    traction_metrics: { users: 3200, mau: 2100, growth_rate_pct: 30 },
    pitch_deck_url: null,
    pitch_deck_filename: "studypal-deck.pdf",
    one_pager_url: null,
    demo_link: null,
    existing_investors: [],
    visibility: "public",
    status: "live",
    created_at: "2026-04-04T00:00:00Z",
    updated_at: "2026-04-06T00:00:00Z",
    founder_profiles: {
      id: "fp-5",
      company_name: "StudyPal",
      one_liner: "AI study groups that match college students by learning style",
      sector: ["EdTech", "AI / ML"],
      calendar_link: "https://calendly.com/studypal/30min",
      company_website: "https://studypal.app",
      accelerator_affiliations: [],
      profiles: {
        id: "p-5",
        full_name: "Alex Kim",
        avatar_url: null,
        linkedin_url: "https://linkedin.com/in/alexkim",
      },
    },
  },
  {
    id: "mock-6",
    instrument_type: "priced_round",
    raise_amount: 3000000,
    amount_raised: 1800000,
    min_check_size: 50000,
    close_date: "2026-05-10",
    traction_metrics: { arr: 420000, users: 89, growth_rate_pct: 18 },
    pitch_deck_url: null,
    pitch_deck_filename: "paybridge-deck.pdf",
    one_pager_url: null,
    demo_link: null,
    existing_investors: ["Stripe", "Abstract Ventures"],
    visibility: "public",
    status: "live",
    created_at: "2026-03-20T00:00:00Z",
    updated_at: "2026-04-05T00:00:00Z",
    founder_profiles: {
      id: "fp-6",
      company_name: "PayBridge",
      one_liner: "Cross-border B2B payments for African exporters",
      sector: ["Fintech"],
      calendar_link: "https://cal.com/paybridge/investor",
      company_website: "https://paybridge.co",
      accelerator_affiliations: ["YC S25", "Google for Startups"],
      profiles: {
        id: "p-6",
        full_name: "Amara Diallo",
        avatar_url: null,
        linkedin_url: "https://linkedin.com/in/amaradiallo",
      },
    },
  },
];

export const MOCK_INTERACTIONS = [
  { id: "int-1", round_drop_id: "mock-3", investor_profile_id: "inv-1", action: "interested", created_at: "2026-04-05T10:00:00Z", updated_at: "2026-04-05T10:00:00Z" },
  { id: "int-2", round_drop_id: "mock-1", investor_profile_id: "inv-1", action: "tracked", created_at: "2026-04-04T15:00:00Z", updated_at: "2026-04-04T15:00:00Z" },
  { id: "int-3", round_drop_id: "mock-6", investor_profile_id: "inv-1", action: "viewed", created_at: "2026-04-06T08:00:00Z", updated_at: "2026-04-06T08:00:00Z" },
];

export const MOCK_INVESTORS = [
  {
    id: "inv-1",
    profile_id: null,
    firm_name: "Precursor Ventures",
    gp_name: "Charles Hudson",
    investor_type: "fund",
    check_size_min: 100000,
    check_size_max: 500000,
    sectors: ["SaaS", "Consumer", "Fintech"],
    stage_preference: ["pre_seed", "seed"],
    thesis: "Investing in the first check for exceptional founders building category-defining companies.",
    notable_exits: "Lattice, Faire",
    value_add: "Hands-on support with fundraising strategy and customer introductions",
    fund_website: "https://precursorvc.com",
    twitter_url: "https://twitter.com/chudson",
    contact_email: null,
    fund_domain: "precursorvc.com",
    slug: "precursor-ventures",
    is_claimed: false,
    claim_token: null,
    claimed_at: null,
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-04-01T00:00:00Z",
    portfolio_companies: [
      { id: "pc-1", investor_profile_id: "inv-1", company_name: "Lattice", round: "seed", check_size: 200000, year: 2016, status: "exited", created_at: "2026-04-01T00:00:00Z" },
    ],
  },
  {
    id: "inv-2",
    profile_id: null,
    firm_name: "Hustle Fund",
    gp_name: "Elizabeth Yin",
    investor_type: "micro_vc",
    check_size_min: 25000,
    check_size_max: 200000,
    sectors: ["AI / ML", "SaaS", "Developer Tools"],
    stage_preference: ["pre_seed"],
    thesis: "Speed matters. We back founders who move fast and break things.",
    notable_exits: null,
    value_add: "Access to a strong community of 1000+ angel investors",
    fund_website: "https://hustlefund.vc",
    twitter_url: "https://twitter.com/dunkhippo33",
    contact_email: null,
    fund_domain: "hustlefund.vc",
    slug: "hustle-fund",
    is_claimed: false,
    claim_token: null,
    claimed_at: null,
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-04-01T00:00:00Z",
    portfolio_companies: [],
  },
  {
    id: "inv-3",
    profile_id: null,
    firm_name: "Pear VC",
    gp_name: "Pejman Nozad",
    investor_type: "fund",
    check_size_min: 250000,
    check_size_max: 1000000,
    sectors: ["AI / ML", "Health / Biotech", "Climate / Energy"],
    stage_preference: ["pre_seed", "seed"],
    thesis: "Partnering with exceptional founders from day one to build iconic companies.",
    notable_exits: "DoorDash, Guardant Health",
    value_add: "Deep Stanford/Silicon Valley network and operational expertise",
    fund_website: "https://pear.vc",
    twitter_url: null,
    contact_email: null,
    fund_domain: "pear.vc",
    slug: "pear-vc",
    is_claimed: false,
    claim_token: null,
    claimed_at: null,
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-04-01T00:00:00Z",
    portfolio_companies: [
      { id: "pc-2", investor_profile_id: "inv-3", company_name: "DoorDash", round: "seed", check_size: 500000, year: 2014, status: "exited", created_at: "2026-04-01T00:00:00Z" },
    ],
  },
  {
    id: "inv-4",
    profile_id: null,
    firm_name: "Afore Capital",
    gp_name: "Anamitra Banerji",
    investor_type: "fund",
    check_size_min: 500000,
    check_size_max: 2000000,
    sectors: ["SaaS", "Developer Tools", "Cybersecurity"],
    stage_preference: ["pre_seed"],
    thesis: "Pre-seed focused. We invest before product-market fit.",
    notable_exits: null,
    value_add: "Help with go-to-market strategy and early hiring",
    fund_website: "https://afore.vc",
    twitter_url: null,
    contact_email: null,
    fund_domain: "afore.vc",
    slug: "afore-capital",
    is_claimed: false,
    claim_token: null,
    claimed_at: null,
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-04-01T00:00:00Z",
    portfolio_companies: [],
  },
  {
    id: "inv-5",
    profile_id: null,
    firm_name: "Contrary Capital",
    gp_name: "Eric Tung",
    investor_type: "fund",
    check_size_min: 100000,
    check_size_max: 750000,
    sectors: ["AI / ML", "EdTech", "Consumer"],
    stage_preference: ["pre_seed", "seed"],
    thesis: "Backing the top founders coming out of the best universities.",
    notable_exits: "Anduril, Ramp",
    value_add: "Access to top engineering talent through university network",
    fund_website: "https://contrary.com",
    twitter_url: null,
    contact_email: null,
    fund_domain: "contrary.com",
    slug: "contrary-capital",
    is_claimed: false,
    claim_token: null,
    claimed_at: null,
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-04-01T00:00:00Z",
    portfolio_companies: [],
  },
  {
    id: "inv-6",
    profile_id: null,
    firm_name: "Soma Capital",
    gp_name: "Gil Penchina",
    investor_type: "syndicate_lead",
    check_size_min: 50000,
    check_size_max: 300000,
    sectors: ["Fintech", "E-commerce", "SaaS"],
    stage_preference: ["seed"],
    thesis: "Fast-moving syndicate that co-invests alongside top-tier VCs.",
    notable_exits: null,
    value_add: "Speed of decision-making and large LP network for follow-on",
    fund_website: "https://somacap.com",
    twitter_url: null,
    contact_email: null,
    fund_domain: "somacap.com",
    slug: "soma-capital",
    is_claimed: false,
    claim_token: null,
    claimed_at: null,
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-04-01T00:00:00Z",
    portfolio_companies: [],
  },
];

export const MOCK_PIPELINE = [
  {
    id: "pipe-1",
    founder_profile_id: "fp-1",
    investor_profile_id: "inv-1",
    status: "deck_shared",
    notes: "Shared deck on Apr 3. Focus on SaaS traction metrics.",
    created_at: "2026-04-02T00:00:00Z",
    updated_at: "2026-04-03T00:00:00Z",
    investor_profiles: MOCK_INVESTORS[0],
  },
  {
    id: "pipe-2",
    founder_profile_id: "fp-1",
    investor_profile_id: "inv-2",
    status: "researching",
    notes: null,
    created_at: "2026-04-05T00:00:00Z",
    updated_at: "2026-04-05T00:00:00Z",
    investor_profiles: MOCK_INVESTORS[1],
  },
  {
    id: "pipe-3",
    founder_profile_id: "fp-1",
    investor_profile_id: "inv-3",
    status: "viewed",
    notes: "Pejman viewed the deck. Waiting for response.",
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-04-06T00:00:00Z",
    investor_profiles: MOCK_INVESTORS[2],
  },
  {
    id: "pipe-4",
    founder_profile_id: "fp-1",
    investor_profile_id: "inv-5",
    status: "meeting_scheduled",
    notes: "Meeting on Apr 10 at 2pm PT.",
    created_at: "2026-04-03T00:00:00Z",
    updated_at: "2026-04-07T00:00:00Z",
    investor_profiles: MOCK_INVESTORS[4],
  },
];

export const MOCK_FOUNDER_ROUNDS = [
  {
    id: "fr-1",
    instrument_type: "safe",
    raise_amount: 1200000,
    amount_raised: 864000,
    min_check_size: 10000,
    close_date: "2026-04-25",
    status: "live",
    valuation_cap: 10000000,
    discount_percent: null,
    traction_metrics: { mrr: 42000, growth_rate_pct: 38, users: 1200 },
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-04-06T00:00:00Z",
  },
  {
    id: "fr-2",
    instrument_type: "safe",
    raise_amount: 500000,
    amount_raised: 500000,
    min_check_size: 5000,
    close_date: "2025-12-15",
    status: "closed",
    valuation_cap: 6000000,
    discount_percent: 20,
    traction_metrics: { users: 300, mrr: 8000 },
    created_at: "2025-10-01T00:00:00Z",
    updated_at: "2025-12-15T00:00:00Z",
  },
];
